import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — ScoutAgent",
};

const sections = [
  {
    label: "01",
    title: "Account Terms",
    content:
      "You must provide a valid email address and create a secure password to use ScoutAgent. You are responsible for maintaining the security of your account credentials. ScoutAgent reserves the right to suspend or terminate accounts that violate these terms.",
  },
  {
    label: "02",
    title: "Acceptable Use",
    content:
      "ScoutAgent is designed for market research and opportunity discovery. You agree not to: use automated tools to scrape or extract data beyond normal usage, redistribute Alpha Card content as a competing service, or use the platform for any illegal purpose.",
  },
  {
    label: "03",
    title: "Payment & Billing",
    content:
      "Pro subscriptions are billed monthly or annually through Stripe. You can cancel at any time — your access continues until the end of the current billing period. Refunds are handled on a case-by-case basis within the first 7 days of a new subscription.",
  },
  {
    label: "04",
    title: "Data & Privacy",
    content:
      "Your use of ScoutAgent is also governed by our Privacy Policy. We collect only what's necessary to provide the service. We do not sell your personal information to third parties.",
  },
  {
    label: "05",
    title: "Intellectual Property",
    content:
      "Alpha Cards and their content are generated by AI based on publicly available information. You may use Alpha Card insights for your own business decisions. The ScoutAgent brand, design, and underlying technology remain our intellectual property.",
  },
  {
    label: "06",
    title: "Termination",
    content:
      "You may delete your account at any time. We may terminate or suspend access to the service immediately, without prior notice, for conduct that we determine violates these Terms or is harmful to other users or the service.",
  },
  {
    label: "07",
    title: "Limitation of Liability",
    content:
      "ScoutAgent provides market intelligence for informational purposes only. We do not guarantee business outcomes based on Alpha Card insights. The service is provided \"as is\" without warranties of any kind. Our total liability is limited to the amount you paid in the 12 months preceding any claim.",
  },
  {
    label: "08",
    title: "Changes to Terms",
    content:
      "We may update these terms from time to time. Significant changes will be communicated via email or an in-app notification. Continued use of the service after changes constitutes acceptance of the updated terms.",
  },
];

export default function TermsPage() {
  return (
    <article>
      <p className="font-mono text-[10px] text-text-dim uppercase tracking-widest mb-2">
        Legal
      </p>
      <h1 className="font-[family-name:var(--font-display)] text-3xl font-bold text-text mb-2">
        Terms of Service
      </h1>
      <p className="font-mono text-xs text-text-dim mb-12">
        Last updated: February 2026
      </p>

      <div className="space-y-10">
        {sections.map((section) => (
          <section key={section.label}>
            <p className="font-mono text-[10px] text-text-dim uppercase tracking-widest mb-2">
              {section.label}
            </p>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-bold text-text mb-4">
              {section.title}
            </h2>
            <p className="font-[family-name:var(--font-serif)] text-sm text-text-muted leading-relaxed">
              {section.content}
            </p>
          </section>
        ))}
      </div>
    </article>
  );
}
