import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  alternates: { canonical: "/terms" },
};

const sections = [
  {
    label: "01",
    title: "About Overheard",
    content:
      "Overheard is a free, open-source project that publishes AI-generated opportunity briefs. There are no accounts, no paid tiers, and no subscriptions. The site is available to everyone at no cost.",
  },
  {
    label: "02",
    title: "Content Disclaimer",
    content:
      "All opportunity briefs (Alpha Cards) are generated by AI and are provided for informational purposes only. They are not financial advice, investment recommendations, or business consulting. Signal strength scores reflect engagement volume, not editorial judgment. Always verify sources and do your own research before making business decisions.",
  },
  {
    label: "03",
    title: "Acceptable Use",
    content:
      "Overheard is open source under the MIT license. You are free to use, modify, and redistribute the code. You may reference Alpha Card insights in your own work. Automated scraping is permitted at reasonable rates — please respect server resources and add a delay between requests.",
  },
  {
    label: "04",
    title: "Intellectual Property",
    content:
      "The Overheard codebase is open source under the MIT license. Alpha Card content is generated from publicly available conversations and may be freely referenced with attribution. The Overheard name and logo are trademarks of the project.",
  },
  {
    label: "05",
    title: "Email Communications",
    content:
      "If you sign up for daily briefs, Overheard will send you one email per day containing that day's opportunity briefs. You can unsubscribe at any time. Overheard does not send marketing emails, promotional content, or share your email with third parties.",
  },
  {
    label: "06",
    title: "Limitation of Liability",
    content:
      "Overheard is provided \"as is\" without warranties of any kind, express or implied. The project and its contributors are not liable for any decisions made based on Alpha Card content, any inaccuracies in AI-generated briefs, or any damages arising from use of the service.",
  },
  {
    label: "07",
    title: "Changes to Terms",
    content:
      "These terms may be updated from time to time. The \"Last updated\" date at the top reflects the most recent revision. Continued use of the site after changes constitutes acceptance of the updated terms.",
  },
];

export default function TermsPage() {
  return (
    <article>
      <p className="font-mono text-[10px] text-text-dim uppercase tracking-widest mb-2">
        Legal
      </p>
      <h1 className="font-[family-name:var(--font-display)] text-3xl font-bold text-text mb-2">
        Terms of Service
      </h1>
      <p className="font-mono text-xs text-text-dim mb-12">
        Last updated: February 2026
      </p>

      <div className="space-y-10">
        {sections.map((section) => (
          <section key={section.label}>
            <p className="font-mono text-[10px] text-text-dim uppercase tracking-widest mb-2">
              {section.label}
            </p>
            <h2 className="font-[family-name:var(--font-display)] text-xl font-bold text-text mb-4">
              {section.title}
            </h2>
            <p className="font-[family-name:var(--font-serif)] text-sm text-text-muted leading-relaxed">
              {section.content}
            </p>
          </section>
        ))}
      </div>
    </article>
  );
}
