import type { Metadata } from "next";
import Link from "next/link";
import { SiteHeader } from "@/components/site-header";
import { SiteFooter } from "@/components/site-footer";
import { JsonLd } from "@/components/json-ld";
import { buildFAQSchema } from "@/lib/json-ld";

export const metadata: Metadata = {
  title: "FAQ",
  description:
    "Frequently asked questions about Overheard — how it works, data sources, signal strength, and more.",
  alternates: { canonical: "/faq" },
};

const faqs = [
  {
    question: "What is Overheard?",
    answer:
      "Overheard is a free, open-source site that publishes AI-generated opportunity briefs every morning. Each brief identifies a demand spike, frustration cluster, or emerging gap where builders could ship something useful, synthesized from signals across Hacker News, Reddit, GitHub, and Product Hunt.",
  },
  {
    question: "What are Alpha Cards?",
    answer:
      "Alpha Cards are structured opportunity briefs. Each card contains a title, thesis, evidence quotes from real conversations, a signal strength score (1–10), and a suggested opportunity. They are designed to help founders and indie hackers spot emerging demand quickly.",
  },
  {
    question: "How does Overheard work?",
    answer:
      "Every morning at 8 AM UTC, an automated pipeline fetches signals from four public sources, clusters them by keyword overlap, scores clusters by engagement and source diversity, and synthesizes the top clusters into opportunity briefs using Google Gemini Flash. The results are committed to a public GitHub repository and auto-deployed.",
  },
  {
    question: "What data sources does Overheard use?",
    answer:
      "Overheard pulls from four sources: Hacker News (front page, Ask HN, Show HN), Reddit (r/SaaS, r/startups, r/Entrepreneur, r/smallbusiness), GitHub (trending repositories created in the last 48 hours), and Product Hunt (daily launches via their Atom feed).",
  },
  {
    question: "Is Overheard free?",
    answer:
      "Yes. Overheard is completely free with no accounts, no paywalls, and no paid tiers. The entire project is open source under the MIT license. It runs on free infrastructure: GitHub Actions, Vercel, and the Gemini Flash free tier.",
  },
  {
    question: "How often is Overheard updated?",
    answer:
      "Overheard publishes new opportunity briefs once per day at 8 AM UTC. The number of cards varies each day (typically 3–10) depending on signal quality — only clusters with sufficient engagement and cross-platform evidence become cards.",
  },
  {
    question: "What does signal strength mean?",
    answer:
      "Signal strength is a score from 1 to 10 that reflects engagement volume and source diversity, not editorial judgment. Higher scores mean more people are discussing the topic across more platforms. It is generated by the AI model based on the underlying evidence.",
  },
  {
    question: "Is Overheard content AI-generated?",
    answer:
      "Yes. All opportunity briefs are generated by Google Gemini Flash based on real signals from public conversations. Every card links back to its original sources so you can verify the evidence. Overheard is a tool for discovery, not financial advice.",
  },
  {
    question: "Who built Overheard?",
    answer:
      "Overheard was built by Leonardo Jaques. The entire project is open source and available on GitHub at github.com/leonardomjq/overheard.",
  },
];

export default function FAQPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <JsonLd data={buildFAQSchema(faqs)} />
      <SiteHeader />
      <main className="flex-1 max-w-3xl mx-auto w-full px-6 py-8">
        <h1 className="font-[family-name:var(--font-display)] text-3xl font-bold mb-10">
          Frequently Asked Questions
        </h1>

        <div className="space-y-8">
          {faqs.map((faq) => (
            <section key={faq.question}>
              <h2 className="font-[family-name:var(--font-display)] text-lg font-semibold mb-2">
                {faq.question}
              </h2>
              <p className="font-[family-name:var(--font-serif)] text-base leading-relaxed text-text-muted">
                {faq.answer}
              </p>
            </section>
          ))}
        </div>

        {/* Cross-links */}
        <div className="mt-12 pt-8 border-t border-border">
          <h2 className="font-mono text-xs uppercase tracking-widest text-text-dim mb-4">
            Learn more
          </h2>
          <div className="flex flex-wrap gap-4">
            <Link
              href="/about"
              className="text-sm text-text-muted hover:text-accent transition-colors underline underline-offset-2"
            >
              How Overheard works
            </Link>
            <Link
              href="/glossary"
              className="text-sm text-text-muted hover:text-accent transition-colors underline underline-offset-2"
            >
              Glossary of terms
            </Link>
            <Link
              href="/archive"
              className="text-sm text-text-muted hover:text-accent transition-colors underline underline-offset-2"
            >
              Browse all editions
            </Link>
          </div>
        </div>
      </main>
      <SiteFooter />
    </div>
  );
}
